- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v6.2.0
  hooks:
  - id: eslint
    types: [file]
    files: \.jsx?$
    additional_dependencies:
    - eslint@6.2.0
    - eslint-config-airbnb@18.0.1
    - eslint-plugin-import@2.18.2
    - eslint-plugin-jsx-a11y@6.2.3
    - eslint-plugin-react@7.14.3
    - eslint-plugin-react-hooks@1.7.0

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.1
  hooks:
  - id: pylint
    exclude: 'wsgi.py|settings.py|manage.py|migrations/'
    args: [
      --max-line-length=120,
      --disable=import-error,
      --disable=missing-docstring,
      --disable=too-few-public-methods,
    ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.720
  hooks:
  - id: mypy
    exclude: 'wsgi.py|settings.py|manage.py|migrations/'
    args: [--no-strict-optional, --ignore-missing-imports] 
