version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            cd frontend
            npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "frontend/package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run tests
          command: |
            cd frontend
            npm test
