version: 2.1
jobs:
  pre_commit_hooks:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Run pre-commit checks
          command: |
            sudo pip install pre-commit==1.18.2
            pre-commit run --all-files pylint
            pre-commit run --all-files mypy
  frontend_tests:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            cd frontend
            npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "frontend/package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run tests
          command: |
            cd frontend
            npm test
  python_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test_reports/
          destination: python_app
workflows:
  version: 2.1
  run_tests:
    jobs:
      - pre_commit_hooks
      - frontend_tests
      - python_tests
