# Generated by Django 2.2.8 on 2020-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(choices=[('JU', 'Jumper'), ('TS', 'T-Shirt'), ('SI', 'Shirt'), ('TR', 'Trousers'), ('SH', 'Shoes')], max_length=2)),
                ('colour', models.CharField(max_length=20)),
                ('additional_details', models.CharField(max_length=150, null=True)),
                ('picture', models.ImageField(upload_to='clothes')),
            ],
        ),
    ]
